### ISSUE TITLE
Adding Autocorrect to the text messages (data)

### ISSUE THREAD

**Issue by brandesdavid** [johan-t/freiFahren#21]
Our data for the text messages are mostly written colloquial and informal. This interferes with the training data.
A solution would be implementing an autocorrect onto the raw data.

E.g. 

Landsbegwr => Landsberger Allee

**Comment by johan-t** [comment]
Tried this but it does not work very well with the data as the stations are often changed to something different. Maybe a custom auto correct would work but that would be to much effort.
